### ISSUE TITLE
How many problem contracts can MAIAN detect today？

### ISSUE THREAD

**Issue by xf97** [ivicanikolicsg/MAIAN#33]
Hello, I am a graduate student from Hohai University. I read your papers on MAIAN, and you can tell me whether there is an increase in the number of contract types that MAIAN can detect today, or whether they are still suicide, profligacy and greedy.

**Comment by etrolik** [comment]
Hi xf97 Can you please check your email. Thanks

**Comment by xf97** [comment]
Done.
